# Generated by Django 4.2 on 2025-04-08 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='namedata',
            options={'verbose_name': 'Данные', 'verbose_name_plural': 'Данные'},
        ),
    ]
