# Generated by Django 4.2 on 2025-04-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0002_alter_namedata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namedata',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
